# Generated by Django 4.2.7 on 2025-09-25 16:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)])),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('license_plate', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(choices=[('TRACTOR', 'Tracteur'), ('STRAIGHT_TRUCK', 'Camion porteur'), ('VAN', 'Fourgonnette')], default='TRACTOR', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='accounts.company')),
            ],
            options={
                'ordering': ['vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(max_length=200)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_location', models.CharField(max_length=200)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('dropoff_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_time', models.DateTimeField(blank=True, null=True)),
                ('current_cycle_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('total_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('actual_duration', models.DurationField(blank=True, null=True)),
                ('load_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in pounds', max_digits=8, null=True)),
                ('trailer_number', models.CharField(blank=True, max_length=20)),
                ('shipping_document', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('PLANNED', 'Planifié'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='PLANNED', max_length=15)),
                ('planned_start_time', models.DateTimeField()),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_data', models.JSONField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField(blank=True)),
                ('stop_type', models.CharField(choices=[('30_MIN_BREAK', 'Pause 30 min'), ('10_HOUR_REST', 'Repos 10h'), ('FUEL', 'Ravitaillement'), ('PICKUP', 'Ramassage'), ('DROPOFF', 'Livraison'), ('MEAL', 'Repas'), ('WEIGH_STATION', 'Station de pesage'), ('INSPECTION', 'Inspection')], max_length=20)),
                ('planned_start_time', models.DateTimeField()),
                ('planned_duration', models.DurationField()),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_duration', models.DurationField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('fuel_gallons', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_stops', to='trips.trip')),
            ],
            options={
                'ordering': ['planned_start_time'],
            },
        ),
        migrations.CreateModel(
            name='TripWaypoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('sequence_order', models.PositiveIntegerField()),
                ('estimated_arrival', models.DateTimeField()),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('distance_from_previous', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='trips.trip')),
            ],
            options={
                'ordering': ['trip', 'sequence_order'],
                'unique_together': {('trip', 'sequence_order')},
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver', 'status'], name='trips_trip_driver__692693_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['planned_start_time'], name='trips_trip_planned_f12c47_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='trips_trip_status_259ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='reststop',
            index=models.Index(fields=['trip', 'planned_start_time'], name='trips_rests_trip_id_2fe1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='reststop',
            index=models.Index(fields=['stop_type'], name='trips_rests_stop_ty_16ff99_idx'),
        ),
    ]
