# Generated by Django 4.2.7 on 2025-09-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='front_image',
            field=models.ImageField(blank=True, help_text='Vue de face du véhicule', null=True, upload_to='vehicles/front/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rear_image',
            field=models.ImageField(blank=True, help_text='Vue arrière du véhicule', null=True, upload_to='vehicles/rear/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='side_image',
            field=models.ImageField(blank=True, help_text='Vue de profil du véhicule', null=True, upload_to='vehicles/side/'),
        ),
    ]
