# Generated by Django 4.2.7 on 2025-09-27 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0002_vehicle_front_image_vehicle_rear_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='assigned_driver',
            field=models.OneToOneField(blank=True, help_text='Conducteur actuellement assigné à ce véhicule', limit_choices_to={'user_type': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude actuelle du véhicule', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude actuelle du véhicule', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_location_update',
            field=models.DateTimeField(blank=True, help_text='Dernière mise à jour de la position', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='operational_status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('IN_USE', 'En utilisation'), ('MAINTENANCE', 'En maintenance'), ('OUT_OF_SERVICE', 'Hors service')], default='AVAILABLE', help_text='Statut opérationnel actuel du véhicule', max_length=20),
        ),
    ]
