# Generated by Django 4.2.7 on 2025-09-29 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0003_vehicle_assigned_driver_vehicle_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reststop',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé cet arrêt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rest_stops_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reststop',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Dernier utilisateur qui a modifié cet arrêt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rest_stops_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé ce voyage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Dernier utilisateur qui a modifié ce voyage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripwaypoint',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé ce point de passage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waypoints_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripwaypoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tripwaypoint',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Dernier utilisateur qui a modifié ce point de passage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waypoints_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé ce véhicule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Dernier utilisateur qui a modifié ce véhicule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
