# Generated by Django 4.2.7 on 2025-10-06 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0004_reststop_created_by_reststop_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes sur cette attribution (raison, conditions spéciales, etc.)')),
                ('end_reason', models.CharField(blank=True, help_text="Raison de la fin d'attribution", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='assigned_driver',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_driver',
            field=models.ForeignKey(blank=True, help_text='Conducteur actuellement assigné à ce véhicule', limit_choices_to={'user_type': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_vehicle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_assignment_date',
            field=models.DateTimeField(blank=True, help_text='Date et heure de la dernière attribution de conducteur', null=True),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['current_driver'], name='trips_vehic_current_f5460a_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['operational_status'], name='trips_vehic_operati_3adc2c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['company', 'operational_status'], name='trips_vehic_company_ab8b22_idx'),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text="Utilisateur qui a fait l'attribution", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'user_type': 'DRIVER'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='ended_by',
            field=models.ForeignKey(blank=True, help_text="Utilisateur qui a terminé l'attribution", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_assignments_ended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='trips.vehicle'),
        ),
        migrations.AddIndex(
            model_name='vehicleassignment',
            index=models.Index(fields=['vehicle', 'start_date'], name='trips_vehic_vehicle_ab6d30_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleassignment',
            index=models.Index(fields=['driver', 'start_date'], name='trips_vehic_driver__c2b7d6_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleassignment',
            index=models.Index(fields=['start_date', 'end_date'], name='trips_vehic_start_d_a562e6_idx'),
        ),
    ]
