# Generated by Django 4.2.7 on 2025-10-06 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0005_vehicleassignment_remove_vehicle_assigned_driver_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-planned_departure']},
        ),
        migrations.RemoveIndex(
            model_name='trip',
            name='trips_trip_planned_f12c47_idx',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='actual_duration',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='actual_end_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='actual_start_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='current_cycle_hours',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='current_lat',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='current_lng',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='dropoff_lat',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='dropoff_lng',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='dropoff_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='estimated_duration',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='load_weight',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='pickup_lat',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='pickup_lng',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='planned_start_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='shipping_document',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='total_distance',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trailer_number',
        ),
        migrations.AddField(
            model_name='trip',
            name='actual_arrival',
            field=models.DateTimeField(blank=True, help_text="Heure d'arrivée réelle", null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='actual_departure',
            field=models.DateTimeField(blank=True, help_text='Heure de départ réelle', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='actual_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance réelle parcourue en kilomètres', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='bill_of_lading',
            field=models.CharField(blank=True, help_text='Numéro de connaissement', max_length=50),
        ),
        migrations.AddField(
            model_name='trip',
            name='cargo_description',
            field=models.CharField(default='Non spécifié', help_text='Description du colis/cargaison à transporter', max_length=300),
        ),
        migrations.AddField(
            model_name='trip',
            name='cargo_special_instructions',
            field=models.TextField(blank=True, help_text='Instructions spéciales pour la cargaison (fragile, réfrigéré, etc.)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='cargo_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valeur déclarée de la cargaison', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='cargo_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Poids de la cargaison en kilogrammes', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Position actuelle - latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Position actuelle - longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='customer_contact',
            field=models.CharField(blank=True, help_text='Contact du client (téléphone/email)', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Nom du client', max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée du voyage'),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_address',
            field=models.CharField(default='Non spécifié', help_text='Adresse de destination', max_length=300),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text="Latitude du point d'arrivée", max_digits=9),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text="Longitude du point d'arrivée", max_digits=9),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_notes',
            field=models.TextField(blank=True, help_text="Notes spéciales pour le lieu d'arrivée"),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_notes',
            field=models.TextField(blank=True, help_text='Notes du conducteur sur le voyage'),
        ),
        migrations.AddField(
            model_name='trip',
            name='estimated_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance estimée en kilomètres', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='estimated_duration_minutes',
            field=models.IntegerField(blank=True, help_text='Durée estimée en minutes', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Notes internes (non visibles par le conducteur)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='last_position_update',
            field=models.DateTimeField(blank=True, help_text='Dernière mise à jour de position', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin_address',
            field=models.CharField(default='Non spécifié', help_text='Adresse de départ', max_length=300),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin_latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Latitude du point de départ', max_digits=9),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin_longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Longitude du point de départ', max_digits=9),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin_notes',
            field=models.TextField(blank=True, help_text='Notes spéciales pour le lieu de départ'),
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_arrival',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Heure d'arrivée planifiée"),
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_departure',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Heure de départ planifiée'),
        ),
        migrations.AddField(
            model_name='trip',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Faible'), ('NORMAL', 'Normal'), ('HIGH', 'Élevée'), ('URGENT', 'Urgent')], default='NORMAL', help_text='Priorité du voyage', max_length=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Numéro de référence client', max_length=50),
        ),
        migrations.AddField(
            model_name='trip',
            name='shipping_documents',
            field=models.JSONField(default=list, help_text='Liste des documents de transport'),
        ),
        migrations.AddField(
            model_name='trip',
            name='title',
            field=models.CharField(default='Deplacement normal', help_text='Titre descriptif du voyage', max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_number',
            field=models.CharField(blank=True, help_text='Numéro de voyage unique', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(help_text='Conducteur assigné au voyage', limit_choices_to={'user_type': 'DRIVER'}, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route_data',
            field=models.JSONField(blank=True, help_text='Données de route calculées (polyline, instructions, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planifié'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='PLANNED', help_text='Statut actuel du voyage', max_length=15),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Véhicule assigné au voyage', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.vehicle'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['vehicle', 'status'], name='trips_trip_vehicle_b6bc2f_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['planned_departure'], name='trips_trip_planned_f3a1b1_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['trip_number'], name='trips_trip_trip_nu_39e2d9_idx'),
        ),
    ]
