# Generated by Django 4.2.7 on 2025-10-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_trip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='actual_route_data',
            field=models.JSONField(blank=True, help_text='Chemin réellement suivi pendant le voyage (points GPS collectés)', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='actual_route_points',
            field=models.JSONField(default=list, help_text='Liste des points GPS du chemin réellement parcouru [[lat, lng, timestamp], ...]'),
        ),
    ]
