# Generated by Django 4.2.7 on 2025-10-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_trip_actual_route_data_trip_actual_route_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='delivery_actual_time',
            field=models.DateTimeField(blank=True, help_text='Heure de livraison réelle', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='delivery_address',
            field=models.CharField(default='Non spécifié', help_text='Adresse de livraison', max_length=300),
        ),
        migrations.AddField(
            model_name='trip',
            name='delivery_company',
            field=models.CharField(blank=True, help_text='Nom de la compagnie à la livraison', max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='delivery_contact',
            field=models.CharField(blank=True, help_text='Contact à la livraison', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='delivery_latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Latitude du point de livraison', max_digits=9),
        ),
        migrations.AddField(
            model_name='trip',
            name='delivery_longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Longitude du point de livraison', max_digits=9),
        ),
        migrations.AddField(
            model_name='trip',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Notes pour la livraison'),
        ),
        migrations.AddField(
            model_name='trip',
            name='delivery_photo',
            field=models.ImageField(blank=True, help_text='Photo de la livraison', null=True, upload_to='trips/delivery_photos/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='delivery_planned_time',
            field=models.DateTimeField(blank=True, help_text='Heure de livraison planifiée', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='delivery_signature',
            field=models.TextField(blank=True, help_text='Signature électronique du destinataire'),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_actual_time',
            field=models.DateTimeField(blank=True, help_text='Heure de ramassage réelle', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_address',
            field=models.CharField(default='Non spécifié', help_text='Adresse de ramassage', max_length=300),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_company',
            field=models.CharField(blank=True, help_text='Nom de la compagnie au ramassage', max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_contact',
            field=models.CharField(blank=True, help_text='Contact au ramassage', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Latitude du point de ramassage', max_digits=9),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Longitude du point de ramassage', max_digits=9),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_notes',
            field=models.TextField(blank=True, help_text='Notes pour le ramassage'),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_planned_time',
            field=models.DateTimeField(blank=True, help_text='Heure de ramassage planifiée', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planifié'), ('AT_PICKUP', 'Au ramassage'), ('IN_TRANSIT', 'En transit'), ('AT_DELIVERY', 'À la livraison'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='PLANNED', help_text='Statut actuel du voyage', max_length=15),
        ),
    ]
