# Generated by Django 4.2.7 on 2025-09-25 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ELDLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_date', models.DateField()),
                ('vehicle_number', models.CharField(max_length=20)),
                ('trailer_number', models.CharField(blank=True, max_length=20)),
                ('shipping_document', models.CharField(blank=True, max_length=50)),
                ('total_miles', models.IntegerField(default=0)),
                ('odometer_start', models.IntegerField(blank=True, null=True)),
                ('odometer_end', models.IntegerField(blank=True, null=True)),
                ('off_duty_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('sleeper_berth_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('driving_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('on_duty_not_driving_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('cycle_hours_used', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('cycle_hours_available', models.DecimalField(decimal_places=2, default=70, max_digits=4)),
                ('has_violations', models.BooleanField(default=False)),
                ('violation_notes', models.TextField(blank=True)),
                ('is_certified', models.BooleanField(default=False)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('signature', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_logs', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_logs', to='trips.trip')),
            ],
            options={
                'ordering': ['-log_date'],
            },
        ),
        migrations.CreateModel(
            name='ELDExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('DOT_INSPECTION', 'Inspection DOT'), ('COMPANY_REPORT', 'Rapport entreprise'), ('DRIVER_REQUEST', 'Demande conducteur'), ('AUDIT', 'Audit')], max_length=20)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('XML', 'XML')], default='PDF', max_length=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_exports', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DutyStatusEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('OFF_DUTY', 'Hors service'), ('SLEEPER_BERTH', 'Couchette'), ('DRIVING', 'Conduite'), ('ON_DUTY_NOT_DRIVING', 'En service (non-conduite)')], max_length=25)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('odometer_reading', models.IntegerField(blank=True, null=True)),
                ('engine_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edit_reason', models.CharField(blank=True, max_length=200)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_duty_entries', to=settings.AUTH_USER_MODEL)),
                ('eld_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_entries', to='eld_logs.eldlog')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='HOSViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violation_type', models.CharField(choices=[('DRIVING_LIMIT', '11-hour driving limit exceeded'), ('DUTY_LIMIT', '14-hour duty limit exceeded'), ('CYCLE_LIMIT', '70-hour cycle limit exceeded'), ('BREAK_REQUIRED', '30-minute break required'), ('REST_REQUIRED', '10-hour rest period required')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], max_length=10)),
                ('description', models.TextField()),
                ('violation_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hos_violations', to=settings.AUTH_USER_MODEL)),
                ('eld_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='eld_logs.eldlog')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-violation_time'],
                'indexes': [models.Index(fields=['driver', 'violation_time'], name='eld_logs_ho_driver__494eb7_idx'), models.Index(fields=['violation_type'], name='eld_logs_ho_violati_ed9780_idx'), models.Index(fields=['is_resolved'], name='eld_logs_ho_is_reso_098266_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='eldlog',
            index=models.Index(fields=['driver', 'log_date'], name='eld_logs_el_driver__a6ad26_idx'),
        ),
        migrations.AddIndex(
            model_name='eldlog',
            index=models.Index(fields=['trip', 'log_date'], name='eld_logs_el_trip_id_37e4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='eldlog',
            index=models.Index(fields=['has_violations'], name='eld_logs_el_has_vio_3e142e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eldlog',
            unique_together={('driver', 'log_date')},
        ),
        migrations.AddIndex(
            model_name='dutystatusentry',
            index=models.Index(fields=['eld_log', 'start_time'], name='eld_logs_du_eld_log_1d613a_idx'),
        ),
        migrations.AddIndex(
            model_name='dutystatusentry',
            index=models.Index(fields=['status'], name='eld_logs_du_status_cbcf05_idx'),
        ),
    ]
