# Generated by Django 4.2.7 on 2025-09-29 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_vehicle_assigned_driver_vehicle_current_latitude_and_more'),
        ('eld_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutystatusentry',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duty_entries', to='trips.trip'),
        ),
    ]
