# Generated by Django 4.2.7 on 2025-09-29 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eld_logs', '0002_dutystatusentry_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutystatusentry',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé cette entrée de statut', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_entries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dutystatusentry',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Dernier utilisateur qui a modifié cette entrée de statut', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_entries_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eldexport',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé cet export', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eldexport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eldexport',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Dernier utilisateur qui a modifié cet export', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eldlog',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé ce journal ELD', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eld_logs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eldlog',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Dernier utilisateur qui a modifié ce journal ELD', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eld_logs_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hosviolation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé cette violation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hosviolation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hosviolation',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Dernier utilisateur qui a modifié cette violation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
