# Generated by Django 4.2.7 on 2025-10-21 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_remove_trip_delivery_actual_time_and_more'),
        ('eld_logs', '0003_dutystatusentry_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eldlog',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eld_logs', to='trips.trip'),
        ),
    ]
