# Generated by Django 4.2.7 on 2025-10-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_logs', '0004_alter_eldlog_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutystatusentry',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
